name: Pipx install from requirements.txt
description: 'Install multiples tools using pipx from a requirements.txt file with caching'
inputs:
  requirements_file:
    description: 'Path to the requirements.txt file'
    required: false
    default: requirements.txt
  other_lock_files:
    description: 'Any other lock files to include for dependency caching'
    required: false

branding:
  icon: package
  color: blue

runs:
  using: "composite"
  steps:
    - name: Get Current Python version
      id: python
      shell: bash
      run: echo "version=$(python -c 'import sys;print(".".join([str(sys.version_info.major),str(sys.version_info.minor),str(sys.version_info.micro)]))')" >> $GITHUB_OUTPUT

    - name: Get Pip Cache Directory
      id: pip
      shell: bash
      run: echo "cache_dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache Pip Dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip.outputs.cache_dir }}
        key: pip-${{ steps.python.outputs.version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(inputs.requirements_file, inputs.other_lock_files) }}
        restore-keys: |
          pip-${{ steps.python.outputs.version }}-${{ runner.os }}-${{ runner.arch }}
          pip-${{ steps.python.outputs.version }}-${{ runner.os }}
          pip-${{ steps.python.outputs.version }}
          pip-

    - name: Install tools
      shell: bash
      run: python ${{ github.action_path }}/action.py ${{ inputs.requirements_file }}
