name: Pipx install from requirements.txt
description: 'Install multiples tools using pipx from a requirements.txt file'
inputs:
  requirements_file:
    description: 'Path to the requirements.txt file'
    required: false
    default: requirements.txt
branding:
  icon: package
  color: blue
runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      run: python ${{ github.action_path }}/action.py ${{ inputs.requirements_file }}
